Tsm 85 large backup s3
wearewondrous/psh-toolbelt pull request #26
Opened 2021-01-06 06:40 UTC by the-wtag

# Background
Large File Upload (files>5GB) is not possible with existing implementation. Have to fix this issue and allow large files to be uploaded.

# Changes
Use `MultipartUploader` instead of  `putObject` as Multipart Upload allow files upload regardless of size limitation.
_Refs: https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-multipart-upload.html_

2021-01-10 11:03 UTC, the-wtag commented
Hello @yobottehg , Regarding TSM-85, Travis is checking using composer v.2 .But my new code pushes was not passing Travis indicating some package version mismatch. So i ran `composer update` and `composer require --dev dealerdirect/phpcodesniffer-composer-installer:"^0.7.0"` (Following this https://github.com/Dealerdirect/phpcodesniffer-composer-installer/issues/119) . But this time composer codestyle is throwing error ( Even if i do same thing with master )
```
hemel@Jontor-Montor:~/Desktop/DrupalWork/Wondrous/devfol/psh-toolbelt$ git stash
No local changes to save
hemel@Jontor-Montor:~/Desktop/DrupalWork/Wondrous/devfol/psh-toolbelt$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
hemel@Jontor-Montor:~/Desktop/DrupalWork/Wondrous/devfol/psh-toolbelt$ composer codestyle
> ./vendor/bin/phpcs
E....E.....E 12 / 12 (100%)



FILE: src/Commands/TestCommands.php
-------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------------------
 8 | ERROR | [x] Non-namespaced classes/interfaces/traits should not be referenced with use statements
   |       |     (Drupal.Classes.UseGlobalClass.RedundantUseStatement)
-------------------------------------------------------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
-------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: src/SiteSettings.php
--------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
--------------------------------------------------------------------------------------------------------------------------------------------------------------
  7 | ERROR | [x] Non-namespaced classes/interfaces/traits should not be referenced with use statements
    |       |     (Drupal.Classes.UseGlobalClass.RedundantUseStatement)
 10 | ERROR | [x] Non-namespaced classes/interfaces/traits should not be referenced with use statements
    |       |     (Drupal.Classes.UseGlobalClass.RedundantUseStatement)
 11 | ERROR | [x] Non-namespaced classes/interfaces/traits should not be referenced with use statements
    |       |     (Drupal.Classes.UseGlobalClass.RedundantUseStatement)
--------------------------------------------------------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: src/Commands/BackupCommands.php
--------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
--------------------------------------------------------------------------------------------------------------------------------------------------------------
  8 | ERROR | [x] Non-namespaced classes/interfaces/traits should not be referenced with use statements
    |       |     (Drupal.Classes.UseGlobalClass.RedundantUseStatement)
  9 | ERROR | [x] Non-namespaced classes/interfaces/traits should not be referenced with use statements
    |       |     (Drupal.Classes.UseGlobalClass.RedundantUseStatement)
 11 | ERROR | [x] Non-namespaced classes/interfaces/traits should not be referenced with use statements
    |       |     (Drupal.Classes.UseGlobalClass.RedundantUseStatement)
--------------------------------------------------------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------------------------------------------------------------------------------------

Time: 137ms; Memory: 8MB

Script ./vendor/bin/phpcs handling the codestyle event returned with error code 2
```
Is this about codestyle changes and we can fix that(Across all those files) in this PR ?

2021-01-10 12:47 UTC, yra-wtag commented
It looks overall good to me. If Rainer suggests us to follow the new guideline then @the-wtag please fix the lint issues

2021-01-10 12:48 UTC, yra-wtag approved these changes

2021-01-11 07:55 UTC, yobottehg requested changes

2021-01-11 07:55 UTC, yobottehg commented on composer.lock
> +            "version": "0.11.20",
You propably get the new sniffs from this update. So if you update phpstan you also need to fix the sniffs

2021-01-12 12:02 UTC, zar-wtag requested changes
Considering the coding standard changes I have suggested a code change that might be in accordance with the standard changes. Please review.

2021-01-12 12:02 UTC, zar-wtag commented on src/Commands/BackupCommands.php
>        $drushPath = Robo::config()->get('drush.path');
```suggestion
      $robo = new \Robo\Robo();
      $drushPath = $robo->config()->get('drush.path');
```

2021-01-12 12:02 UTC, zar-wtag commented on src/Commands/BackupCommands.php
> +        'bucket' => Robo::config()->get('storage.s3.upload_bucket'),
```suggestion
        'bucket' => $robo->config()->get('storage.s3.upload_bucket'),
```

2021-01-12 12:02 UTC, zar-wtag commented on src/Commands/BackupCommands.php
> +          'bucket' => Robo::config()->get('storage.s3.upload_bucket'),
```suggestion
          'bucket' => $robo->config()->get('storage.s3.upload_bucket'),
```

2021-01-13 03:32 UTC, bas-wtag approved these changes

2021-01-14 05:46 UTC, the-wtag commented
TravisCI is green and Code is functional ( Tested from `integra` PR)

2021-01-14 05:57 UTC, zar-wtag approved these changes
Looks good to me. Code changes were explained.

2021-01-14 08:56 UTC, yobottehg approved these changes
LGTM. Please merge and tag a 2.1.0 release

2021-01-14 11:52 UTC, MustafizurRahmanWelldev approved these changes

2021-01-17 10:56 UTC, merged