TSM-407 File Backup Issue Fix
wearewondrous/psh-toolbelt pull request #28
Opened 2021-07-01 04:04 UTC by the-wtag

# Background
Currently if any exception occurs within the block where the backup files are created, the `unlink()` doesn't run properly. As a result dumped file to create backup is not cleared and takes up environment space. That sometimes results subsequent file dump effort into failure. 

# Possible Solution
Make sure that created dump file will be deleted for sure if there is any exception or not.

# Technical Hint
- `unlink` is moved to `finally` block.
- Successful Purge is reported as `info`
- Any Failure in purge operation is reported as `error`

2021-07-01 05:27 UTC, bia-wtag approved these changes
LGTM.

2021-07-01 06:12 UTC, zar-wtag approved these changes
Tested in the pr looks good. I would still like to consider the scenario we talked about on Op fail if php breaks down in the middle of a backup.

2021-07-01 06:51 UTC, luxflux requested changes
This fixes the tmp file issue on Dufry, but why is it failing on Dufry anyway? Don't we have to address that as well?

2021-07-01 06:58 UTC, the-wtag commented
> This fixes the tmp file issue on Dufry, but why is it failing on Dufry anyway? Don't we have to address that as well?

If the recent memory space addition fixes this for dufry, then we can think that the issue is happening for dufry specifically because of it's growing files and db size against limited space. Otherwise we'll have to investigate in depth.

2021-07-05 03:41 UTC, bas-wtag approved these changes

2021-07-07 06:09 UTC, adi-wtag approved these changes

2021-07-07 09:02 UTC, Wickeey approved these changes
looks good to me. i think we can just try it and see if it works in live conditions. if its working as intended - great, if not, doesnt matter we have status quo and have to look at it again.

2021-07-07 09:05 UTC, Wickeey commented
> > This fixes the tmp file issue on Dufry, but why is it failing on Dufry anyway? Don't we have to address that as well?
> 
> If the recent disk space addition fixes this for dufry, then we can think that the issue is happening for dufry specifically because of it's growing files and db size against limited space. Otherwise we'll have to investigate in depth.

yes this is solved. there wasnt even enough space left to create 1 complete backup. this is solved by increasing the discspace by 5gb

2021-07-07 11:48 UTC, the-wtag commented
> intended

@Wickeey We tried to test that in live condition here https://github.com/wearewondrous/dufry/pull/64 .Please Review

2021-07-07 15:32 UTC, luxflux approved these changes

2021-07-11 04:32 UTC, merged

2023-08-17 06:27 UTC, the-wtag commented
Relevant Ticket: https://parkside-interactive.atlassian.net/browse/TSM-402